lib/la_famiglia_web/router.ex
defmodule LaFamigliaWeb.Router do
  use LaFamiglia.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug LaFamigliaWeb.Plugs.AssignDefaults
  end

  pipeline :api do
    plug :accepts, ["json"]

    plug :fetch_session
    plug :protect_from_forgery
  end

  pipeline :ingame do
    plug LaFamigliaWeb.Plugs.Authentication, "/"
    plug LaFamigliaWeb.Plugs.Timer
    plug LaFamigliaWeb.Plugs.VillaLoader
    plug LaFamigliaWeb.Plugs.VillaChecker
    plug LaFamigliaWeb.Plugs.VillaProcessor
  end

  scope "/", LaFamigliaWeb do
    # Use the default browser stack
    pipe_through :browser

    resources "/session", SessionController,
      only: [:create, :new, :delete],
      singleton: true

    resources "/players", PlayerController, only: [:create, :new]

    scope "/" do
      pipe_through :ingame

      resources "/players", PlayerController, only: [:index]

      resources "/villas", VillaController, only: [:index, :show] do
        resources "/building_queue_items", BuildingQueueItemController, only: [:create]
        resources "/unit_queue_items", UnitQueueItemController, only: [:create]
        resources "/attack_movements", AttackMovementController, only: [:new, :create]

        resources "/reports", ReportController, only: [:index]
      end

      resources "/building_queue_items", BuildingQueueItemController, only: [:delete]
      resources "/unit_queue_items", UnitQueueItemController, only: [:delete]

      resources "/movements", MovementController, only: [:index]

      resources "/conversations", ConversationController, only: [:index, :show] do
        resources "/messages", MessageController, only: [:create]
      end

      resources "/messages", MessageController, only: [:create]
      resources "/reports", ReportController, only: [:index, :show]

      get "/map/:x/:y", MapController, :show

      get "/help", HelpController, :index
    end

    get "/", PageController, :index
  end

  scope "/api/v1", LaFamigliaWeb.Api do
    pipe_through :api

    scope "/" do
      pipe_through :ingame

      scope "/players" do
        get "/search/:query", PlayerController, :search
      end

      resources "/villas", VillaController, only: [] do
        resources "/attack_movements", AttackMovementController, only: [:create]
      end

      get "/map", MapController, :show
    end
  end
end

lib/la_famiglia_web/views/layout_view.ex
defmodule LaFamigliaWeb.LayoutView do
  use LaFamiglia.Web, :view
end

lib/la_famiglia_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>La Famiglia – un’offerta nessuno può rifiutare</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= if @current_player do %>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">La Famiglia</a>
          </div>
          <div class="navbar-collapse collapse">
            <%= if @current_villa do %>
              <ul class="nav navbar-nav">
                <li><%= link coordinates(@current_villa), to: Routes.villa_path(@conn, :show, @current_villa)%></li>
                <li><%= link "Villas", to: Routes.villa_path(@conn, :index) %></li>
                <li><%= link "Troops", to: Routes.movement_path(@conn, :index) %></li>
                <li><%= link "Map", to: Routes.map_path(@conn, :show, @current_villa.x, @current_villa.y) %></li>
                <li>
                  <%= link to: Routes.conversation_path(@conn, :index) do %>
                    Messages
                    <%= unread_conversations_badge(@current_player) %>
                  <% end %>
                </li>
                <li><%= link "Reports", to: Routes.report_path(@conn, :index) %></li>
                <li><%= link "Ranking", to: Routes.player_path(@conn, :index) %></li>
                <li><%= link "Help", to: Routes.help_path(@conn, :index) %></li>
              </ul>
            <% end %>

            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-user"></span> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete %></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    <% end %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

          <%= @inner_content %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>